export enum SCENES {
  INTRO = 'INTRO',
  MAP = 'MAP',
  MISSION_1 = 'MISSION_1',
  MISSION_2 = 'MISSION_2',
  MISSION_3 = 'MISSION_3',
  BRANCH_1 = 'BRANCH_1',
  BRANCH_2 = 'BRANCH_2',
  BRANCH_3 = 'BRANCH_3',
  FINALE = 'FINALE'
}
